services:
  web:
    network_mode: host
    build:
      context: .
      dockerfile: services/web.Dockerfile
    profiles: [prod, fakeprod]
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      afs:
        condition: service_healthy
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  afs:
    network_mode: host
    build:
      context: .
      dockerfile: services/afs.Dockerfile
      args:
        AFS_PASSWORD: ${AFS_PASSWORD}
    profiles: [dev, prod, fakeprod, migrate, seed]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    network_mode: host
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles: [dev, prod, fakeprod, postgres, migrate, seed]
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    network_mode: host
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --address ":${MINIO_PORT}" --console-address ":${MINIO_CONSOLE_PORT}" /data
    profiles: [dev, prod, fakeprod, migrate, seed]
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    network_mode: host
    image: caddy/caddy
    environment:
      - BASE_URL=${BASE_URL}
      - NEXT_PUBLIC_MINIO_ENDPOINT=${NEXT_PUBLIC_MINIO_ENDPOINT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    profiles: [prod]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 9443:9443
      - 9443:9443/udp
      - 2019:2019
    depends_on:
      web:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "${BASE_URL}/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    network_mode: host
    build:
      context: .
      dockerfile: services/migrate.Dockerfile
    profiles: [migrate]
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      afs:
        condition: service_healthy

  seed:
    network_mode: host
    build:
      context: .
      dockerfile: services/seed.Dockerfile
    profiles: [seed]
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      afs:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:
  caddy_data:
  caddy_config:
